"use client";
import Image from "next/image";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { apiGet } from "@/lib/api";
import type { Product } from "@/types/api";

export default function ProductDetailPage() {
  const params = useParams<{ id: string }>(); const [product, setProduct] = useState<Product | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { apiGet<Product>(`/admin/products/${params.id}`).then(setProduct).catch((reason: Error) => setMessage(reason.message)); }, [params.id]);
  return <main className="mx-auto max-w-7xl px-4 py-8"><div className="mb-6 flex items-center justify-between"><div><p className="text-sm text-slate-500">Quan ly san pham / Chi tiet</p><h1 className="text-3xl font-bold text-slate-950">{product?.name ?? "Chi tiet san pham"}</h1></div><div className="flex gap-3"><Link href={`/admin/products/${params.id}/edit`} className="rounded-md bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Sua</Link><Link href="/admin/products" className="py-2 text-sm font-semibold">Quay lai</Link></div></div>{message ? <p className="text-sm text-rose-700">{message}</p> : product ? <div className="grid gap-6 lg:grid-cols-[1fr_2fr]"><section className="rounded-md border border-slate-200 bg-white p-5"><h2 className="font-bold">Hinh anh</h2><div className="mt-4 grid grid-cols-2 gap-3">{product.images?.map((image) => <div key={image.id} className={`overflow-hidden rounded-md border ${image.is_primary ? "border-teal-700" : "border-slate-200"}`}><Image src={image.path} alt={image.alt_text || product.name} width={480} height={480} unoptimized className="aspect-square w-full object-contain" /><p className="px-2 py-1 text-xs text-slate-500">{image.is_primary ? "Anh dai dien" : ""}</p></div>)}</div></section><section className="grid gap-6"><div className="rounded-md border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Thong tin chung</h2><p className="mt-2 text-slate-600">{product.short_description || "Khong co mo ta ngan."}</p><dl className="mt-5 grid gap-4 sm:grid-cols-3"><div><dt className="text-xs text-slate-500">Danh muc</dt><dd>{product.category?.name ?? "-"}</dd></div><div><dt className="text-xs text-slate-500">Thuong hieu</dt><dd>{product.brand?.name ?? "-"}</dd></div><div><dt className="text-xs text-slate-500">Trang thai</dt><dd>{product.status}</dd></div></dl></div><div className="rounded-md border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Tat ca bien the</h2><span className="text-sm text-slate-500">{product.variants?.length ?? 0} bien the</span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-100"><tr><th className="p-3">Ten</th><th className="p-3">SKU</th><th className="p-3">Gia</th><th className="p-3">Ton kho</th><th className="p-3">Trang thai</th></tr></thead><tbody>{product.variants?.map((variant) => <tr key={variant.id} className="border-t border-slate-200"><td className="p-3 font-semibold">{variant.name}{variant.is_default ? " (Mac dinh)" : ""}</td><td className="p-3">{variant.sku}</td><td className="p-3">{variant.sale_price ?? variant.price}</td><td className="p-3">{variant.stock_quantity}</td><td className="p-3">{variant.active ? "Dang ban" : "Da tat"}</td></tr>)}</tbody></table></div></div></section></div> : <p className="text-sm text-slate-500">Dang tai...</p>}</main>;
}
