"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { useConfirm } from "@/contexts/ConfirmContext";
import { Pagination } from "@/components/admin/shared/Pagination";
import { usePaginatedAdminRows } from "@/hooks/admin/usePaginatedAdminRows";
import { apiDeleteResponse } from "@/lib/api";
import { formatVnd } from "@/lib/format";
import type { Promotion } from "@/types/api";

export default function PromotionsPage() {
  const confirm = useConfirm(); const { rows, meta, message, setMessage, params, queryString, router } = usePaginatedAdminRows<Promotion>("/admin/promotions"); const [query, setQuery] = useState(params.get("q") ?? "");
  function search(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const next = new URLSearchParams(queryString); if (query) next.set("q", query); else next.delete("q"); next.delete("page"); router.push(`/admin/promotions?${next.toString()}`); }
  function filter(key: string, value: string) { const next = new URLSearchParams(queryString); if (value) next.set(key, value); else next.delete(key); next.delete("page"); router.push(`/admin/promotions?${next.toString()}`); }
  async function remove(row: Promotion) { if (!(await confirm({ title: "Xóa mã khuyến mãi?", message: `Xóa ${row.code}?`, confirmLabel: "Xóa" }))) return; try { const response = await apiDeleteResponse<null>(`/admin/promotions/${row.id}`); setMessage(response.message); router.refresh(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Không thể xử lý mã khuyến mãi."); } }
  return <main className="mx-auto max-w-7xl px-4 py-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold text-slate-950">Khuyến mãi</h1><p className="mt-1 text-sm text-slate-500">Quản lý mã giảm giá và phạm vi áp dụng.</p></div><Link href="/admin/promotions/create" className="rounded-md bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Thêm khuyến mãi</Link></div><form onSubmit={search} className="mb-3 flex flex-wrap gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm mã khuyến mãi" className="h-10 rounded-md border border-slate-300 px-3 text-sm" /><button className="rounded-md border border-slate-300 px-4 text-sm font-semibold">Tìm</button><select aria-label="Lọc loại mã" value={params.get("type") ?? ""} onChange={(event) => filter("type", event.target.value)} className="h-10 rounded-md border border-slate-300 px-3 text-sm"><option value="">Tất cả loại</option><option value="percent">Phần trăm</option><option value="fixed">Số tiền</option></select><select aria-label="Lọc trạng thái" value={params.get("active") ?? ""} onChange={(event) => filter("active", event.target.value)} className="h-10 rounded-md border border-slate-300 px-3 text-sm"><option value="">Tất cả trạng thái</option><option value="1">Đang hoạt động</option><option value="0">Đã tắt</option></select></form>{message ? <p className="mb-3 text-sm text-rose-700">{message}</p> : null}<div className="overflow-x-auto rounded-md border border-slate-200 bg-white"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-100"><tr><th className="p-3">Mã</th><th className="p-3">Giá trị</th><th className="p-3">Đơn tối thiểu</th><th className="p-3">Đã dùng</th><th className="p-3">Trạng thái</th><th className="p-3">Thao tác</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id} className="border-t border-slate-200"><td className="p-3 font-semibold">{row.code}</td><td className="p-3">{row.type === "percent" ? `${row.value}%` : formatVnd(row.value)}</td><td className="p-3">{formatVnd(row.min_order_amount)}</td><td className="p-3">{row.used_count}/{row.usage_limit ?? "-"}</td><td className="p-3">{row.active ? "Đang hoạt động" : "Đã tắt"}</td><td className="flex gap-2 p-3"><Link href={`/admin/promotions/${row.id}/edit`} className="rounded-md border border-slate-300 px-3 py-2 font-semibold">Sửa</Link><button type="button" disabled={(row.usages_count ?? 0) > 0} onClick={() => void remove(row)} className="rounded-md border border-slate-300 px-3 py-2 font-semibold disabled:opacity-40">Xóa</button></td></tr>) : <tr><td colSpan={6} className="p-8 text-center text-slate-500">Không có mã khuyến mãi phù hợp.</td></tr>}</tbody></table><Pagination meta={meta} /></div></main>;
}
