"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";

import { Pagination } from "@/components/admin/Pagination";
import { useConfirm } from "@/contexts/ConfirmContext";
import { ApiError, apiDelete, apiGetPaginated } from "@/lib/api";
import type { PaginatedMeta, User } from "@/types/api";
import { useAuth } from "@/contexts/AuthContext";

const emptyMeta: PaginatedMeta = { current_page: 1, last_page: 1, total: 0 };

export default function UsersPage() {
  const router = useRouter(); const confirm = useConfirm(); const { user: currentUser } = useAuth(); const params = useSearchParams(); const queryString = params.toString();
  const [rows, setRows] = useState<User[]>([]); const [meta, setMeta] = useState(emptyMeta); const [query, setQuery] = useState(params.get("q") ?? ""); const [message, setMessage] = useState("");
  useEffect(() => { void apiGetPaginated<User>(`/admin/users${queryString ? `?${queryString}` : ""}`).then(({ data, meta: nextMeta }) => { setRows(data); setMeta(nextMeta); }).catch((reason: Error) => { if (reason instanceof ApiError && reason.status === 401) router.push("/admin/login"); else setMessage(reason.message); }); }, [queryString, router]);
  function search(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const next = new URLSearchParams(queryString); if (query) next.set("q", query); else next.delete("q"); next.delete("page"); router.push(`/admin/users${next.toString() ? `?${next.toString()}` : ""}`); }
  async function remove(row: User) { if (row.id === currentUser?.id) { setMessage("Khong the xoa tai khoan dang dang nhap."); return; } if (!(await confirm({ title: "Xoa tai khoan?", message: `Xoa ${row.email}?`, confirmLabel: "Xoa" }))) return; try { await apiDelete(`/admin/users/${row.id}`); router.refresh(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Khong the xoa."); } }
  function filter(key: string, value: string) { const next = new URLSearchParams(queryString); if (value) next.set(key, value); else next.delete(key); next.delete("page"); router.push(`/admin/users${next.toString() ? `?${next.toString()}` : ""}`); }
  return <main className="mx-auto max-w-7xl px-4 py-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold text-slate-950">Tài khoản</h1><p className="mt-1 text-sm text-slate-500">Quản lý người dùng và quyền truy cập.</p></div><div className="flex gap-2"><form onSubmit={search} className="flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm tên, email" className="h-10 rounded-md border border-slate-300 px-3 text-sm" /><button className="rounded-md border border-slate-300 px-4 text-sm font-semibold">Tìm</button></form><Link href="/admin/users/create" className="rounded-md bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Thêm tài khoản</Link></div></div><div className="mb-5 flex flex-wrap gap-2"><select aria-label="Lọc vai trò" value={params.get("role") ?? ""} onChange={(event) => filter("role", event.target.value)} className="h-10 rounded-md border border-slate-300 px-3 text-sm"><option value="">Tất cả vai trò</option><option value="admin">Quản trị viên</option><option value="manager">Quản lý</option><option value="staff">Nhân viên</option><option value="member">Thành viên</option></select><select aria-label="Lọc trạng thái" value={params.get("status") ?? ""} onChange={(event) => filter("status", event.target.value)} className="h-10 rounded-md border border-slate-300 px-3 text-sm"><option value="">Tất cả trạng thái</option><option value="active">Đang hoạt động</option><option value="locked">Đã khóa</option></select></div>{message ? <p className="mb-3 text-sm text-rose-700">{message}</p> : null}<div className="overflow-x-auto rounded-md border border-slate-200 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-100"><tr><th className="p-3">Tài khoản</th><th className="p-3">Số điện thoại</th><th className="p-3">Vai trò</th><th className="p-3">Trạng thái</th><th className="p-3">Đơn hàng</th><th className="p-3">Thao tác</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id} className="border-t border-slate-200"><td className="p-3"><Link href={`/admin/users/${row.id}`} className="font-semibold hover:underline">{row.name}</Link><span className="block text-slate-500">{row.email}</span></td><td className="p-3">{row.phone ?? "-"}</td><td className="p-3">{row.role}</td><td className="p-3">{row.status}</td><td className="p-3">{row.orders_count ?? 0}</td><td className="flex gap-2 p-3"><Link href={`/admin/users/${row.id}/edit`} className="rounded-md border border-slate-300 px-3 py-2 font-semibold">Sửa</Link><button type="button" disabled={row.id === currentUser?.id} onClick={() => void remove(row)} className="rounded-md border border-slate-300 px-3 py-2 font-semibold disabled:opacity-40">Xóa</button></td></tr>) : <tr><td colSpan={6} className="p-8 text-center text-slate-500">Không có tài khoản phù hợp.</td></tr>}</tbody></table><Pagination meta={meta} /></div></main>;
}
