"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useConfirm } from "@/contexts/ConfirmContext";
import { ApiError, apiDelete, apiGetList } from "@/lib/api";
import type { User } from "@/types/api";
import { useAuth } from "@/contexts/AuthContext";
export default function UsersPage() {
  const router = useRouter(); const confirm = useConfirm(); const { user: currentUser } = useAuth(); const [rows, setRows] = useState<User[]>([]); const [query, setQuery] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(() => apiGetList<User>(`/admin/users${query ? `?q=${encodeURIComponent(query)}` : ""}`).then(setRows).catch((reason: Error) => { if (reason instanceof ApiError && reason.status === 401) router.push("/admin/login"); else setMessage(reason.message); }), [query, router]);
  useEffect(() => { void load(); }, [load]);
  async function remove(row: User) { if (row.id === currentUser?.id) return setMessage("Khong the xoa tai khoan dang dang nhap."); if (!(await confirm({ title: "Xoa tai khoan?", message: `Xoa ${row.email}?`, confirmLabel: "Xoa" }))) return; try { await apiDelete(`/admin/users/${row.id}`); void load(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Khong the xoa."); } }
  function search(event: FormEvent<HTMLFormElement>) { event.preventDefault(); void load(); }
  return <main className="mx-auto max-w-7xl px-4 py-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold text-slate-950">Tai khoan</h1><p className="mt-1 text-sm text-slate-500">Quan ly nguoi dung va quyen truy cap.</p></div><div className="flex gap-2"><form onSubmit={search} className="flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tim ten, email" className="h-10 rounded-md border border-slate-300 px-3 text-sm" /><button className="rounded-md border border-slate-300 px-4 text-sm font-semibold">Tim</button></form><Link href="/admin/users/create" className="rounded-md bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Them tai khoan</Link></div></div>{message ? <p className="mb-3 text-sm text-rose-700">{message}</p> : null}<div className="overflow-hidden rounded-md border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-100"><tr><th className="p-3">Tai khoan</th><th className="p-3">So dien thoai</th><th className="p-3">Vai tro</th><th className="p-3">Trang thai</th><th className="p-3">Don hang</th><th className="p-3">Thao tac</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-slate-200"><td className="p-3"><Link href={`/admin/users/${row.id}`} className="font-semibold hover:underline">{row.name}</Link><span className="block text-slate-500">{row.email}</span></td><td className="p-3">{row.phone ?? "-"}</td><td className="p-3">{row.role}</td><td className="p-3">{row.status}</td><td className="p-3">{row.orders_count ?? 0}</td><td className="flex gap-2 p-3"><Link href={`/admin/users/${row.id}/edit`} className="rounded-md border border-slate-300 px-3 py-2 font-semibold">Sua</Link><button type="button" disabled={row.id === currentUser?.id} onClick={() => void remove(row)} className="rounded-md border border-slate-300 px-3 py-2 font-semibold disabled:opacity-40">Xoa</button></td></tr>)}</tbody></table></div></main>;
}
