<?php

use App\Http\Controllers\Api\V1\AccountAddressController;
use App\Http\Controllers\Api\V1\AccountOrderController;
use App\Http\Controllers\Api\V1\Admin\BannerController;
use App\Http\Controllers\Api\V1\Admin\BrandController;
use App\Http\Controllers\Api\V1\Admin\CategoryController;
use App\Http\Controllers\Api\V1\Admin\ContactController;
use App\Http\Controllers\Api\V1\Admin\DashboardController;
use App\Http\Controllers\Api\V1\Admin\MenuController;
use App\Http\Controllers\Api\V1\Admin\OrderController;
use App\Http\Controllers\Api\V1\Admin\PageController;
use App\Http\Controllers\Api\V1\Admin\PostCategoryController;
use App\Http\Controllers\Api\V1\Admin\PostController;
use App\Http\Controllers\Api\V1\Admin\ProductController;
use App\Http\Controllers\Api\V1\Admin\PromotionController;
use App\Http\Controllers\Api\V1\Admin\SettingController;
use App\Http\Controllers\Api\V1\Admin\StockController;
use App\Http\Controllers\Api\V1\Admin\UploadController;
use App\Http\Controllers\Api\V1\Admin\UserController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\CartController;
use App\Http\Controllers\Api\V1\CatalogController;
use App\Http\Controllers\Api\V1\CheckoutController;
use App\Http\Controllers\Api\V1\ReviewController;
use App\Http\Controllers\Api\V1\VnpayController;
use App\Http\Controllers\Api\V1\WishlistController;
use App\Http\Middleware\EnsureAccountActive;
use App\Http\Middleware\EnsureAdmin;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::get('homepage', [CatalogController::class, 'homepage']);
    Route::get('categories', [CatalogController::class, 'categories']);
    Route::get('brands', [CatalogController::class, 'brands']);
    Route::get('products', [CatalogController::class, 'products']);
    Route::get('products/{product:slug}', [CatalogController::class, 'product']);
    Route::get('search', [CatalogController::class, 'search']);
    Route::get('posts', [CatalogController::class, 'posts']);
    Route::get('posts/{post:slug}', [CatalogController::class, 'post']);
    Route::get('post-categories', [CatalogController::class, 'postCategories']);
    Route::get('pages/{page:slug}', [CatalogController::class, 'page']);
    Route::post('contact', [CatalogController::class, 'contact'])->middleware('throttle:5,1');
    Route::post('cart/quote', [CartController::class, 'quote']);
    Route::post('promotions/validate', [CartController::class, 'validatePromotion']);
    Route::post('checkout', [CheckoutController::class, 'store']);
    Route::get('vnpay/return', [VnpayController::class, 'return']);
    Route::get('vnpay/ipn', [VnpayController::class, 'ipn']);
    Route::post('auth/register', [AuthController::class, 'register']);
    Route::post('auth/login', [AuthController::class, 'login']);
    Route::post('auth/forgot-password', [AuthController::class, 'forgotPassword']);
    Route::post('auth/reset-password', [AuthController::class, 'resetPassword']);

    Route::middleware(['auth:sanctum', EnsureAccountActive::class])->group(function (): void {
        Route::get('auth/me', [AuthController::class, 'me']);
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::patch('account/profile', [AuthController::class, 'updateProfile']);
        Route::post('account/change-password', [AuthController::class, 'changePassword']);
        Route::apiResource('account/addresses', AccountAddressController::class)->except(['show']);
        Route::get('account/orders', [AccountOrderController::class, 'index']);
        Route::get('account/orders/{code}/invoice', [AccountOrderController::class, 'invoice']);
        Route::get('account/orders/{code}', [AccountOrderController::class, 'show']);
        Route::post('account/orders/{code}/cancel', [AccountOrderController::class, 'cancel']);
        Route::get('wishlist', [WishlistController::class, 'index']);
        Route::post('wishlist', [WishlistController::class, 'store']);
        Route::delete('wishlist/{product}', [WishlistController::class, 'destroy']);
        Route::post('products/{product}/reviews', [ReviewController::class, 'store']);
        Route::get('cart', [CartController::class, 'index']);
        Route::post('cart/items', [CartController::class, 'addItem']);
        Route::patch('cart/items/{item}', [CartController::class, 'updateItem']);
        Route::delete('cart/items/{item}', [CartController::class, 'deleteItem']);
        Route::post('cart/merge', [CartController::class, 'merge']);
    });

    Route::prefix('admin')->middleware(['auth:sanctum', EnsureAccountActive::class, EnsureAdmin::class])->group(function (): void {
        Route::get('dashboard', DashboardController::class);
        Route::get('uploads/images', [UploadController::class, 'index']);
        Route::post('uploads/images', [UploadController::class, 'image']);
        Route::delete('uploads/images', [UploadController::class, 'destroy']);
        Route::apiResource('brands', BrandController::class);
        Route::apiResource('categories', CategoryController::class);
        Route::get('products/export', [ProductController::class, 'export']);
        Route::apiResource('products', ProductController::class);
        Route::apiResource('promotions', PromotionController::class);
        Route::apiResource('users', UserController::class);
        Route::apiResource('post-categories', PostCategoryController::class);
        Route::apiResource('posts', PostController::class);
        Route::apiResource('pages', PageController::class);
        Route::apiResource('menus', MenuController::class);
        Route::apiResource('banners', BannerController::class);
        Route::apiResource('contacts', ContactController::class)->only(['index', 'show', 'update', 'destroy']);
        Route::get('settings', [SettingController::class, 'index']);
        Route::put('settings', [SettingController::class, 'update']);
        Route::get('stock', [StockController::class, 'index']);
        Route::post('stock', [StockController::class, 'store']);
        Route::get('stock/movements', [StockController::class, 'movements']);
        Route::get('orders', [OrderController::class, 'index']);
        Route::get('orders/export', [OrderController::class, 'export']);
        Route::get('orders/{order}/invoice', [OrderController::class, 'invoice']);
        Route::get('orders/{order}', [OrderController::class, 'show']);
        Route::patch('orders/{order}/status', [OrderController::class, 'updateStatus']);
    });
});
