"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ApiError, apiGet, apiPatch, apiPost } from "@/lib/api";
import type { User } from "@/types/api";

type Form = { name: string; email: string; phone: string; password: string; role: User["role"]; status: User["status"] };
const blank: Form = { name: "", email: "", phone: "", password: "", role: "member", status: "active" };
export function UserForm({ id }: { id?: string }) {
  const router = useRouter(); const [form, setForm] = useState<Form>(blank); const [errors, setErrors] = useState<Record<string, string[]>>({}); const [loading, setLoading] = useState(Boolean(id)); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { if (!id) return; apiGet<User>(`/admin/users/${id}`).then((user) => setForm({ name: user.name, email: user.email, phone: user.phone ?? "", password: "", role: user.role, status: user.status })).catch((reason: Error) => setMessage(reason.message)).finally(() => setLoading(false)); }, [id]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); setErrors({}); try { const payload = { name: form.name, email: form.email, phone: form.phone || undefined, password: form.password || undefined, role: form.role, status: form.status }; if (id) await apiPatch(`/admin/users/${id}`, payload); else await apiPost("/admin/users", { ...payload, password: form.password }); router.push("/admin/users"); } catch (reason) { if (reason instanceof ApiError) setErrors(reason.errors); setMessage(reason instanceof Error ? reason.message : "Không thể lưu tài khoản."); } finally { setSaving(false); } }
  if (loading) return <p className="text-sm text-slate-500">Đang tải...</p>;
  return <form onSubmit={submit} className="grid max-w-4xl gap-5 rounded-md border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2"><Field label="Họ và tên" error={errors.name?.[0]} value={form.name} required onChange={(name) => setForm({ ...form, name })} /><Field label="Email" error={errors.email?.[0]} type="email" value={form.email} required onChange={(email) => setForm({ ...form, email })} /><Field label="Số điện thoại" error={errors.phone?.[0]} value={form.phone} onChange={(phone) => setForm({ ...form, phone })} /><Field label={id ? "Mật khẩu mới" : "Mật khẩu"} error={errors.password?.[0]} type="password" value={form.password} required={!id} onChange={(password) => setForm({ ...form, password })} /></div><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Vai trò<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as Form["role"] })} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3 font-normal"><option value="member">Thành viên</option><option value="staff">Nhân viên</option><option value="manager">Quản lý</option><option value="admin">Quản trị viên</option></select></label><label className="text-sm font-semibold text-slate-700">Trạng thái<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as Form["status"] })} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3 font-normal"><option value="active">Đang hoạt động</option><option value="locked">Đã khóa</option></select></label></div>{message ? <p className="text-sm text-rose-700">{message}</p> : null}<div className="flex gap-2"><button disabled={saving} className="rounded-md bg-slate-950 px-5 py-3 text-sm font-semibold text-white">{saving ? "Đang lưu..." : "Lưu tài khoản"}</button><button type="button" onClick={() => router.push("/admin/users")} className="rounded-md border border-slate-300 px-5 py-3 text-sm font-semibold">Hủy</button></div></form>;
}
function Field({ label, value, onChange, type = "text", required = false, error }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean; error?: string }) { return <label className="text-sm font-semibold text-slate-700">{label}<input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3 font-normal" />{error ? <span className="mt-1 block text-xs font-normal text-rose-700">{error}</span> : null}</label>; }
