"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ApiError, apiGet, apiPatch, apiPost } from "@/lib/api";
import { slugify } from "@/lib/slug";

export type EntityField = { key: string; label: string; type?: "text" | "number" | "textarea" | "select" | "checkbox"; options?: { value: string; label: string }[]; required?: boolean };
export function AdminEntityForm({ endpoint, id, fields, backUrl, submitLabel }: { endpoint: string; id?: string; fields: EntityField[]; backUrl: string; submitLabel: string }) {
  const router = useRouter(); const [values, setValuesState] = useState<Record<string, string | boolean>>(() => Object.fromEntries(fields.map((field) => [field.key, field.type === "checkbox" ? false : field.options?.[0]?.value ?? ""]))); const [errors, setErrors] = useState<Record<string, string>>({}); const slugEdited = useRef(Boolean(id)); const setValues = (next: Record<string, string | boolean>) => setValuesState((current) => { const source = typeof next.name === "string" ? "name" : typeof next.title === "string" ? "title" : null; const sourceChanged = source ? next[source] !== current[source] : false; const slugChanged = next.slug !== current.slug; if (slugChanged && !sourceChanged) slugEdited.current = true; return source && sourceChanged && !slugEdited.current && typeof next.slug === "string" ? { ...next, slug: slugify(String(next[source])) } : next; }); const [loading, setLoading] = useState(Boolean(id)); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { if (!id) return; apiGet<Record<string, unknown>>(`${endpoint}/${id}`).then((record) => setValues(Object.fromEntries(fields.map((field) => [field.key, typeof record[field.key] === "boolean" ? record[field.key] as boolean : String(record[field.key] ?? "")])))).catch((reason: Error) => setMessage(reason.message)).finally(() => setLoading(false)); }, [endpoint, fields, id]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setErrors({}); try { if (id) await apiPatch(`${endpoint}/${id}`, values); else await apiPost(endpoint, values); router.push(backUrl); } catch (reason) { if (reason instanceof ApiError) { setErrors(Object.fromEntries(Object.entries(reason.errors).map(([key, messages]) => [key, messages[0] ?? reason.message]))); setMessage(reason.message); } else setMessage(reason instanceof Error ? reason.message : "Không thể lưu dữ liệu."); } finally { setSaving(false); } }
  if (loading) return <p className="text-sm text-slate-500">Đang tải...</p>;
  return <form onSubmit={submit} className="grid max-w-4xl gap-5 rounded-md border border-slate-200 bg-white p-6 shadow-sm">{fields.map((field) => field.type === "textarea" ? <label key={field.key} className="text-sm font-semibold text-slate-700">{field.label}<textarea required={field.required} value={String(values[field.key] ?? "")} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })} className="mt-1 min-h-36 w-full rounded-md border border-slate-300 px-3 py-2 font-normal" />{errors[field.key] ? <span className="mt-1 block text-xs font-normal text-rose-700">{errors[field.key]}</span> : null}</label> : field.type === "checkbox" ? <label key={field.key} className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={Boolean(values[field.key])} onChange={(event) => setValues({ ...values, [field.key]: event.target.checked })} />{field.label}</label> : <label key={field.key} className="text-sm font-semibold text-slate-700">{field.label}{field.type === "select" ? <select required={field.required} value={String(values[field.key] ?? "")} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3 font-normal">{field.options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input required={field.required} type={field.type ?? "text"} value={String(values[field.key] ?? "")} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3 font-normal" />} {errors[field.key] ? <span className="mt-1 block text-xs font-normal text-rose-700">{errors[field.key]}</span> : null}</label>)}{message ? <p className="text-sm text-rose-700">{message}</p> : null}<div className="flex gap-2"><button disabled={saving} className="rounded-md bg-slate-950 px-5 py-3 text-sm font-semibold text-white">{saving ? "Đang lưu..." : submitLabel}</button><button type="button" onClick={() => router.push(backUrl)} className="rounded-md border border-slate-300 px-5 py-3 text-sm font-semibold">Hủy</button></div></form>;
}
