"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { apiGet, apiPatch, apiPost } from "@/lib/api";
import type { User } from "@/types/api";

type Form = { name: string; email: string; phone: string; password: string; role: User["role"]; status: User["status"] };
const blank: Form = { name: "", email: "", phone: "", password: "", role: "member", status: "active" };
export function UserForm({ id }: { id?: string }) {
  const router = useRouter(); const [form, setForm] = useState<Form>(blank); const [loading, setLoading] = useState(Boolean(id)); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { if (!id) return; apiGet<User>(`/admin/users/${id}`).then((user) => setForm({ name: user.name, email: user.email, phone: user.phone ?? "", password: "", role: user.role, status: user.status })).catch((reason: Error) => setMessage(reason.message)).finally(() => setLoading(false)); }, [id]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); try { const payload = { name: form.name, email: form.email, phone: form.phone || undefined, password: form.password || undefined, role: form.role, status: form.status }; if (id) await apiPatch(`/admin/users/${id}`, payload); else await apiPost("/admin/users", { ...payload, password: form.password }); router.push("/admin/users"); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Khong the luu tai khoan."); } finally { setSaving(false); } }
  if (loading) return <p className="text-sm text-slate-500">Dang tai...</p>;
  return <form onSubmit={submit} className="grid max-w-4xl gap-5 rounded-md border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2"><Field label="Ho va ten" value={form.name} required onChange={(name) => setForm({ ...form, name })} /><Field label="Email" type="email" value={form.email} required onChange={(email) => setForm({ ...form, email })} /><Field label="So dien thoai" value={form.phone} onChange={(phone) => setForm({ ...form, phone })} /><Field label={id ? "Mat khau moi" : "Mat khau"} type="password" value={form.password} required={!id} onChange={(password) => setForm({ ...form, password })} /></div><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Vai tro<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as Form["role"] })} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3 font-normal"><option value="member">Thanh vien</option><option value="staff">Nhan vien</option><option value="manager">Quan ly</option><option value="admin">Quan tri vien</option></select></label><label className="text-sm font-semibold text-slate-700">Trang thai<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as Form["status"] })} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3 font-normal"><option value="active">Dang hoat dong</option><option value="locked">Da khoa</option></select></label></div>{message ? <p className="text-sm text-rose-700">{message}</p> : null}<div className="flex gap-2"><button disabled={saving} className="rounded-md bg-slate-950 px-5 py-3 text-sm font-semibold text-white">{saving ? "Dang luu..." : "Luu tai khoan"}</button><button type="button" onClick={() => router.push("/admin/users")} className="rounded-md border border-slate-300 px-5 py-3 text-sm font-semibold">Huy</button></div></form>;
}
function Field({ label, value, onChange, type = "text", required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="text-sm font-semibold text-slate-700">{label}<input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-slate-300 px-3 font-normal" /></label>; }
