"use client";

import Link from "next/link";
import { useConfirm } from "@/contexts/ConfirmContext";
import { Pagination } from "@/components/admin/Pagination";
import { usePaginatedAdminRows } from "@/hooks/usePaginatedAdminRows";
import { apiDeleteResponse } from "@/lib/api";
import type { Page as ContentPage } from "@/types/api";

export default function ContentPagesPage() {
  const confirm = useConfirm(); const { rows, meta, message, setMessage, params, queryString, router } = usePaginatedAdminRows<ContentPage>("/admin/pages");
  async function remove(row: ContentPage) { if (!(await confirm({ title: "Xóa trang?", message: `Xóa ${row.title}?`, confirmLabel: "Xóa" }))) return; try { const response = await apiDeleteResponse<null>(`/admin/pages/${row.id}`); setMessage(response.message); router.refresh(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Không thể xử lý trang."); } }
  return <main className="mx-auto max-w-7xl px-4 py-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold text-slate-950">Trang nội dung</h1><p className="mt-1 text-sm text-slate-500">Quản lý các trang giới thiệu và chính sách.</p></div><Link href="/admin/pages/create" className="rounded-md bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Thêm trang</Link></div><div className="mb-5 flex flex-wrap gap-2"><input defaultValue={params.get("q") ?? ""} onKeyDown={(event) => { if (event.key !== "Enter") return; const next = new URLSearchParams(queryString); const value = event.currentTarget.value.trim(); if (value) next.set("q", value); else next.delete("q"); next.delete("page"); router.push(`/admin/pages?${next.toString()}`); }} placeholder="Tìm tiêu đề" className="h-10 rounded-md border border-slate-300 px-3 text-sm" /><select aria-label="Lọc trạng thái" value={params.get("status") ?? ""} onChange={(event) => { const next = new URLSearchParams(queryString); if (event.target.value) next.set("status", event.target.value); else next.delete("status"); next.delete("page"); router.push(`/admin/pages?${next.toString()}`); }} className="h-10 rounded-md border border-slate-300 px-3 text-sm"><option value="">Tất cả trạng thái</option><option value="published">Đã xuất bản</option><option value="draft">Bản nháp</option></select></div>{message ? <p className="mb-3 text-sm text-rose-700">{message}</p> : null}<div className="overflow-x-auto rounded-md border border-slate-200 bg-white"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-100"><tr><th className="p-3">Tiêu đề</th><th className="p-3">Slug</th><th className="p-3">Trạng thái</th><th className="p-3">Thao tác</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id} className="border-t border-slate-200"><td className="p-3 font-semibold">{row.title}</td><td className="p-3">{row.slug}</td><td className="p-3">{row.status === "published" ? "Đã xuất bản" : "Bản nháp"}</td><td className="flex gap-2 p-3"><Link href={`/admin/pages/${row.id}/edit`} className="rounded-md border border-slate-300 px-3 py-2 font-semibold">Sửa</Link><button type="button" onClick={() => void remove(row)} className="rounded-md border border-slate-300 px-3 py-2 font-semibold">Xóa</button></td></tr>) : <tr><td colSpan={4} className="p-8 text-center text-slate-500">Chưa có trang nội dung.</td></tr>}</tbody></table><Pagination meta={meta} /></div></main>;
}
